# Generated by Django 4.1.5 on 2023-02-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_recipe_dish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
