# Generated by Django 4.1.5 on 2023-02-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_remove_recipe_user_recipe_chef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='chef',
            new_name='user',
        ),
    ]
