# Generated by Django 4.1.5 on 2023-02-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
