# Generated by Django 4.1.5 on 2023-02-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_profile_email_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
